# Generated by Django 3.2.7 on 2021-09-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_note_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='denominator',
            field=models.IntegerField(default=20),
        ),
    ]
