# Generated by Django 3.2.7 on 2021-09-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_note_denominator'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
