# Generated by Django 3.2.7 on 2021-09-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_note_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dark_color',
            field=models.CharField(default='#7417D5', max_length=7),
        ),
        migrations.AddField(
            model_name='course',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
