# Generated by Django 3.2.7 on 2021-10-14 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211014_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalisationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='examdate',
            name='date',
        ),
        migrations.AddField(
            model_name='examdate',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examdate',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='tp_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_tp_groups', to='courses.tpgroup'),
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localisation_images', to='courses.localisationimage')),
            ],
        ),
        migrations.AddField(
            model_name='examdate',
            name='localisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_localisations', to='courses.localisation'),
        ),
    ]
