# Generated by Django 3.2.7 on 2021-10-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211004_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
