# Generated by Django 3.2.7 on 2021-10-11 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_semester_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
