# Generated by Django 3.2.7 on 2021-10-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20211014_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
