# Generated by Django 3.2.7 on 2021-10-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_examdate_tp_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='acroynm',
            field=models.CharField(default='', max_length=16),
        ),
    ]
