# Generated by Django 3.2.7 on 2022-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_acroynm_course_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('acronym', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='tpgroup',
            name='td_group',
        ),
        migrations.RemoveField(
            model_name='examdate',
            name='tp_group',
        ),
        migrations.DeleteModel(
            name='TdGroup',
        ),
    ]
