# Generated by Django 3.2.7 on 2022-09-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220907_1911'),
        ('user_sessions', '0009_auto_20220907_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TpGroup',
        ),
        migrations.AddField(
            model_name='semester',
            name='degree',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_degree', to='courses.degree'),
        ),
    ]
