# Generated by Django 3.2.7 on 2022-09-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20220907_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='activated',
        ),
    ]
