# Generated by Django 3.2.7 on 2021-09-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_sessions', '0003_alter_session_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.TextField(default='lqLVqgtH', editable=False, max_length=8),
        ),
    ]
