# Generated by Django 3.2.7 on 2021-09-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0004_alter_session_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.TextField(default='BE0OM0W9', editable=False, max_length=8, unique=True),
        ),
    ]
