# Generated by Django 3.2.7 on 2021-10-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211004_0930'),
        ('user_sessions', '0006_auto_20210927_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='tp_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_tp_groups', to='courses.tpgroup'),
        ),
    ]
