# Generated by Django 3.2.7 on 2021-10-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0007_auto_20211014_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='planning_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
