# Generated by Django 3.2.7 on 2021-10-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_tpgroup_id'),
        ('user_sessions', '0008_sessionselectedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='tp_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_tp_groups', to='courses.tpgroup'),
        ),
    ]
