# Generated by Django 3.2.7 on 2022-09-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220907_1911'),
        ('user_sessions', '0008_session_planning_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='tp_group',
        ),
        migrations.AddField(
            model_name='session',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_degrees', to='courses.degree'),
        ),
    ]
