# Generated by Django 3.2.7 on 2022-10-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_semester_activated'),
        ('user_sessions', '0009_auto_20220907_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='degree',
        ),
        migrations.AddField(
            model_name='session',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_semesters', to='courses.semester'),
        ),
    ]
